"""
Curated learning-resource lookup.

Design decision: resource URLs are NOT generated by the LLM. Asking a model
to produce URLs is a well-known hallucination trap (plausible-looking but
dead/incorrect links). Instead, this module keeps a small, hand-verified
table of real, stable documentation URLs, keyed by topic keyword, and
matches roadmap skills/task titles against it deterministically.

This trades broad coverage for correctness: an unmatched topic gets a safe,
generic fallback (a roadmap.sh search link) rather than an invented URL.
Extending coverage is a matter of adding rows to `_RESOURCE_TABLE` - no
prompt changes required.
"""
from __future__ import annotations

from typing import NamedTuple


class Resource(NamedTuple):
    label: str
    url: str


# Keyword (lowercase, matched as a substring of the skill/task title) ->
# curated resources. Order matters only for readability; lookup is
# substring-based so keep keywords reasonably specific.
_RESOURCE_TABLE: dict[str, list[Resource]] = {
    "fastapi": [
        Resource("FastAPI Official Docs", "https://fastapi.tiangolo.com/"),
    ],
    "python": [
        Resource("Python Official Docs", "https://docs.python.org/3/"),
    ],
    "pydantic": [
        Resource("Pydantic Docs", "https://docs.pydantic.dev/latest/"),
    ],
    "postgres": [
        Resource("PostgreSQL Official Docs", "https://www.postgresql.org/docs/"),
    ],
    "sql": [
        Resource("SQL - freeCodeCamp", "https://www.freecodecamp.org/news/tag/sql/"),
    ],
    "docker": [
        Resource("Docker Official Docs", "https://docs.docker.com/"),
    ],
    "kubernetes": [
        Resource("Kubernetes Official Docs", "https://kubernetes.io/docs/home/"),
    ],
    "git": [
        Resource("Git Official Docs", "https://git-scm.com/doc"),
    ],
    "javascript": [
        Resource("JavaScript - MDN", "https://developer.mozilla.org/en-US/docs/Web/JavaScript"),
    ],
    "typescript": [
        Resource("TypeScript Official Docs", "https://www.typescriptlang.org/docs/"),
    ],
    "react": [
        Resource("React Official Docs", "https://react.dev/learn"),
    ],
    "node": [
        Resource("Node.js Official Docs", "https://nodejs.org/en/docs"),
    ],
    "html": [
        Resource("HTML - MDN", "https://developer.mozilla.org/en-US/docs/Web/HTML"),
    ],
    "css": [
        Resource("CSS - MDN", "https://developer.mozilla.org/en-US/docs/Web/CSS"),
    ],
    "rest api": [
        Resource("REST API design - MDN", "https://developer.mozilla.org/en-US/docs/Glossary/REST"),
    ],
    "authentication": [
        Resource("Web authentication - MDN", "https://developer.mozilla.org/en-US/docs/Web/Security/Authentication"),
    ],
    "jwt": [
        Resource("JWT Introduction - jwt.io", "https://jwt.io/introduction"),
    ],
    "testing": [
        Resource("pytest Docs", "https://docs.pytest.org/en/stable/"),
    ],
    "ci/cd": [
        Resource("GitHub Actions Docs", "https://docs.github.com/en/actions"),
    ],
    "linux": [
        Resource("Linux Command Line - freeCodeCamp", "https://www.freecodecamp.org/news/tag/linux/"),
    ],
    "azure": [
        Resource("Microsoft Learn - Azure", "https://learn.microsoft.com/en-us/azure/"),
    ],
    "c#": [
        Resource("C# Docs - Microsoft Learn", "https://learn.microsoft.com/en-us/dotnet/csharp/"),
    ],
    ".net": [
        Resource(".NET Docs - Microsoft Learn", "https://learn.microsoft.com/en-us/dotnet/"),
    ],
    "aws": [
        Resource("AWS Documentation", "https://docs.aws.amazon.com/"),
    ],
    "machine learning": [
        Resource("Machine Learning - freeCodeCamp", "https://www.freecodecamp.org/news/tag/machine-learning/"),
    ],
    "data structures": [
        Resource("Data Structures - freeCodeCamp", "https://www.freecodecamp.org/news/tag/data-structures/"),
    ],
    "algorithm": [
        Resource("Algorithms - freeCodeCamp", "https://www.freecodecamp.org/news/tag/algorithms/"),
    ],
    "mongodb": [
        Resource("MongoDB Manual", "https://www.mongodb.com/docs/manual/"),
    ],
    "redis": [
        Resource("Redis Docs", "https://redis.io/docs/latest/"),
    ],
    "graphql": [
        Resource("GraphQL Official Docs", "https://graphql.org/learn/"),
    ],
}

_FALLBACK_LABEL = "roadmap.sh topic search"


def _fallback_resource(topic: str) -> Resource:
    query = topic.strip().replace(" ", "%20")
    return Resource(_FALLBACK_LABEL, f"https://roadmap.sh/search?q={query}")


def resources_for_topic(topic: str, limit: int = 2) -> list[Resource]:
    """Return up to `limit` curated resources whose keyword matches `topic`
    (case-insensitive substring match either direction). Falls back to a
    roadmap.sh search link if nothing matches, to avoid ever returning an
    empty or hallucinated resource list."""
    topic_lower = topic.lower()
    matches: list[Resource] = []

    for keyword, resources in _RESOURCE_TABLE.items():
        if keyword in topic_lower or topic_lower in keyword:
            for r in resources:
                if r not in matches:
                    matches.append(r)
        if len(matches) >= limit:
            break

    if not matches:
        matches = [_fallback_resource(topic)]

    return matches[:limit]
